services:
  - type: web
    name: despierta-kids
    runtime: node
    buildCommand: npm install && npm run build
    startCommand: npm run dev
    envVars:
      - key: NODE_ENV
        value: production
